openapi: 3.0.0
info:
  title: Cat Info API
  contact:
    email: contact@catfact.ninja
  version: 1.0.0
servers: 
  - url: https://af0eda6e-cb76-4f14-b52f-8a0f9c6f26c4.mock.pstmn.io
    description: Postman mock
  - url: https://catfact.ninja
    description: prod
paths:
  /breeds:
    get:
      tags:
        - Breeds
      description: Returns a a list of breeds
      operationId: getBreeds
      parameters:
        - name: limit
          in: query
          description: This is a description
          required: false
          schema:
            type: integer
            format: int64
            default: 2
      responses:
        '200':
          description: Normal operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Breed'
  /fact:
    get:
      tags:
        - Facts
      description: Returns a random fact
      operationId: getRandomFact
      parameters:
        - name: max_length
          in: query
          description: maximum length of returned fact
          required: false
          schema:
            type: integer
            format: int64
            default: 200
      responses:
        '200':
          description: Normal response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatFact'
        '404':
          description: Fact not found
  /facts:
    get:
      tags:
        - Facts
      summary: Get a list of facts
      description: Returns a a list of facts
      operationId: getFacts
      parameters:
        - name: max_length
          in: query
          required: false
          schema:
            type: integer
            format: int64
            default: 200
        - name: limit
          in: query
          description: limit the amount of results returned
          required: false
          schema:
            type: integer
            format: int64
            default: 2
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CatFact'
components:
  schemas:
    Breed:
      title: Breed model
      description: Breed
      properties:
        breed:
          title: Breed
          description: Breed
          type: string
          format: string
        country:
          title: Country
          description: Country
          type: string
          format: string
        origin:
          title: Origin
          description: Origin
          type: string
          format: string
        coat:
          title: Coat
          description: Coat
          type: string
          format: string
        pattern:
          title: Pattern
          description: Pattern
          type: string
          format: string
      type: object
    CatFact:
      title: CatFact model
      description: CatFact
      properties:
        name:
          title: Fact
          description: Fact
          type: string
          format: string
        length:
          title: Length
          description: Length
          type: integer
          format: int32
          default: 200
      type: object
    CatName:
      title: Cat name model
      description: CatName
      properties:
        CatName:
          title: CatName
          description: Name for the cat
          type: string
          format: string
      type: object      
tags:
  - name: Facts
    description: Cat Facts
  - name: Breeds
    description: Breeds
#security:
#    - CatAPIKey: []            